### ISSUE TITLE
Can you give more details of reproduce the paper results?

### ISSUE THREAD

**Issue by maohbao** [facebookresearch/mlqe#3]
Hi Marina,

Thank you very much for the job. I want to reproduce the results, but can you give me more details about how to do this? 

After I installed fairseq, how to get the QE score for an input sentence during translation?  I shall modify the transformer decoder code of fairseq to get more information during decode, is not it? Can you provide more information about how to do this? Thank you very much!

Bao

**Comment by mfomicheva** [comment]
Hi Bao,
Thanks a lot for your interest. You have instructions and some scripts to reproduce the results here: https://github.com/pytorch/fairseq/tree/master/examples/unsupervised_quality_estimation
Please, let me know if you have any further questions

**Comment by maohbao** [comment]
Thank you very much, I will try it!
